const STATES=["Andhra Pradesh","Arunachal Pradesh","Assam","Bihar","Chhattisgarh","Goa","Gujarat","Haryana","Himachal Pradesh","Jharkhand","Karnataka","Kerala","Madhya Pradesh","Maharashtra","Manipur","Meghalaya","Mizoram","Nagaland","Odisha","Punjab","Rajasthan","Sikkim","Tamil Nadu","Telangana","Tripura","Uttar Pradesh","Uttarakhand","West Bengal"];
const I18N={
en:{eyebrow:"FARMER STORAGE SUPPORT",title:"Find Cold Storage & Warehouses",subtitle:"Explore storage options for your harvest, compare facilities, and contact providers.",searchTitle:"Search by location and crop",state:"State",district:"District",districtPlaceholder:"Enter district",crop:"Crop / commodity",facility:"Facility type",search:"Search facilities",reset:"Reset",notice:"Demo directory: listings below are sample records, not verified live availability or current prices. Call the facility to confirm.",results:"Storage facilities",guideTitle:"Before storing your crop",tip1:"Ask about storage temperature, humidity, and crop suitability.",tip2:"Confirm rent, minimum quantity, duration, loading/unloading, and insurance.",tip3:"Get a receipt and written terms; inspect the facility before paying.",footer:"Smart Crop Advisory • Storage directory demo",allCrops:"All crops",allFacilities:"All facilities",cold:"Cold storage",warehouse:"Warehouse",sample:"Sample listing",capacity:"Capacity",crops:"Suitable crops",location:"Location",call:"Call facility",empty:"No sample facilities match. Try another state or choose “All facilities”."},
hi:{eyebrow:"किसानों के लिए भंडारण सहायता",title:"कोल्ड स्टोरेज और वेयरहाउस खोजें",subtitle:"अपनी फसल के लिए भंडारण विकल्प देखें और सुविधा से संपर्क करें।",searchTitle:"स्थान और फसल से खोजें",state:"राज्य",district:"जिला",districtPlaceholder:"जिले का नाम लिखें",crop:"फसल / वस्तु",facility:"सुविधा का प्रकार",search:"सुविधाएँ खोजें",reset:"रीसेट",notice:"डेमो सूची: नीचे दिए रिकॉर्ड उदाहरण हैं; लाइव उपलब्धता या मौजूदा किराया सत्यापित नहीं है। पुष्टि के लिए फोन करें।",results:"भंडारण सुविधाएँ",guideTitle:"फसल रखने से पहले",tip1:"तापमान, नमी और फसल के अनुकूल होने की जानकारी लें।",tip2:"किराया, न्यूनतम मात्रा, अवधि, लोडिंग-अनलोडिंग और बीमा पूछें।",tip3:"रसीद और लिखित शर्तें लें; भुगतान से पहले जगह देखें।",footer:"स्मार्ट क्रॉप एडवाइजरी • भंडारण डेमो",allCrops:"सभी फसलें",allFacilities:"सभी सुविधाएँ",cold:"कोल्ड स्टोरेज",warehouse:"वेयरहाउस",sample:"उदाहरण सूची",capacity:"क्षमता",crops:"उपयुक्त फसलें",location:"स्थान",call:"सुविधा को कॉल करें",empty:"मेल खाती नमूना सुविधा नहीं मिली। दूसरा राज्य चुनें या सभी सुविधाएँ चुनें।"},
bho:{eyebrow:"किसान खातिर भंडारण मदद",title:"कोल्ड स्टोरेज आ गोदाम खोजीं",subtitle:"अपना फसल रखे के जगह देखीं आ सुविधा से संपर्क करीं।",searchTitle:"जगह आ फसल से खोजीं",state:"राज्य",district:"जिला",districtPlaceholder:"जिला के नाम लिखीं",crop:"फसल / सामान",facility:"सुविधा के प्रकार",search:"सुविधा खोजीं",reset:"रीसेट",notice:"डेमो सूची: नीचे के जानकारी नमूना बा; असली उपलब्धता आ किराया पक्का नइखे। पुष्टि खातिर फोन करीं।",results:"भंडारण सुविधा",guideTitle:"फसल रखे से पहिले",tip1:"तापमान, नमी आ फसल खातिर सही बा कि ना, पूछीं।",tip2:"किराया, कम से कम मात्रा, समय, चढ़ाई-उतराई आ बीमा पूछीं।",tip3:"रसीद आ लिखित शर्त लीं; पैसा देवे से पहिले जगह देखीं।",footer:"स्मार्ट क्रॉप एडवाइजरी • भंडारण डेमो",allCrops:"सब फसल",allFacilities:"सब सुविधा",cold:"कोल्ड स्टोरेज",warehouse:"गोदाम",sample:"नमूना सूची",capacity:"क्षमता",crops:"लायक फसल",location:"जगह",call:"सुविधा पर फोन करीं",empty:"मिलत-जुलत नमूना सुविधा नइखे। दोसरा राज्य चुनीं या सब सुविधा चुनीं।"}
};
// Keep sample listings visibly labelled. Replace/add records with verified provider data before public use.
const SAMPLE=[
{name:"Demo Cold Store A",state:"Uttar Pradesh",district:"Ghaziabad",type:"cold",capacity:"500 MT (sample)",crops:["Potato","Onion","Vegetables"],phone:"",address:"Example listing — address not verified"},
{name:"Demo Grain Warehouse B",state:"Uttar Pradesh",district:"Meerut",type:"warehouse",capacity:"1,000 MT (sample)",crops:["Wheat","Rice"],phone:"",address:"Example listing — address not verified"},
{name:"Demo Produce Store C",state:"Maharashtra",district:"Nashik",type:"cold",capacity:"300 MT (sample)",crops:["Apple","Vegetables","Onion"],phone:"",address:"Example listing — address not verified"},
{name:"Demo Warehouse D",state:"Punjab",district:"Ludhiana",type:"warehouse",capacity:"750 MT (sample)",crops:["Wheat","Rice"],phone:"",address:"Example listing — address not verified"},
{name:"Demo Cold Store E",state:"Himachal Pradesh",district:"Shimla",type:"cold",capacity:"250 MT (sample)",crops:["Apple","Vegetables"],phone:"",address:"Example listing — address not verified"},
{name:"Demo Grain Store F",state:"Madhya Pradesh",district:"Indore",type:"warehouse",capacity:"600 MT (sample)",crops:["Wheat","Rice"],phone:"",address:"Example listing — address not verified"}
];
const $=id=>document.getElementById(id);let lang="en";
STATES.forEach(s=>{let o=document.createElement("option");o.value=s;o.textContent=s;$("state").appendChild(o)});
function translate(){const d=I18N[lang];document.documentElement.lang=lang==="bho"?"hi":lang;document.querySelectorAll("[data-i18n]").forEach(el=>{let k=el.dataset.i18n;if(d[k])el.textContent=d[k]});document.querySelectorAll("[data-i18n-placeholder]").forEach(el=>el.placeholder=d[el.dataset.i18nPlaceholder]);$("crop").options[0].text=d.allCrops;$("type").options[0].text=d.allFacilities;$("type").options[1].text=d.cold;$("type").options[2].text=d.warehouse;render()}
function render(){let state=$("state").value,district=$("district").value.trim().toLowerCase(),crop=$("crop").value,type=$("type").value;let items=SAMPLE.filter(x=>(!state||x.state===state)&&(!district||x.district.toLowerCase().includes(district))&&(type==="all"||x.type===type)&&(crop==="all"||x.crops.includes(crop)));$("count").textContent=items.length;$("cards").innerHTML="";if(!items.length){$("cards").innerHTML=`<div class="empty">${I18N[lang].empty}</div>`;return}items.forEach(x=>{let article=document.createElement("article");article.className="facility";let d=I18N[lang];article.innerHTML=`<div class="facility-top"><span class="tag">${d[x.type]}</span><span class="tag">${d.sample}</span></div><h3></h3><p class="meta"></p><p><b>${d.capacity}:</b> </p><p><b>${d.crops}:</b> </p><p class="meta"></p>`;article.querySelector("h3").textContent=x.name;article.querySelectorAll("p")[0].textContent=`${x.district}, ${x.state}`;article.querySelectorAll("p")[1].append(document.createTextNode(x.capacity));article.querySelectorAll("p")[2].append(document.createTextNode(x.crops.join(", ")));article.querySelectorAll("p")[3].textContent=x.address;let a=document.createElement("span");a.className="contact";a.textContent=d.call+" — "+(x.phone||"phone not supplied");a.style.opacity=".75";article.append(a);$("cards").append(article)})}
$("language").addEventListener("change",e=>{lang=e.target.value;translate()});$("searchBtn").addEventListener("click",render);$("resetBtn").addEventListener("click",()=>{$("state").value="";$("district").value="";$("crop").value="all";$("type").value="all";render()});$("district").addEventListener("input",render);$("state").addEventListener("change",render);$("crop").addEventListener("change",render);$("type").addEventListener("change",render);translate();