[build]
<<<<<<< HEAD
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/api/recommend"
  to = "/.netlify/functions/recommend"
  status = 200

[[redirects]]
=======
  functions = "netlify/functions"

[[redirects]]
>>>>>>> f88917de9e1179878ae13cf42269820599a2244a
  from = "/api/analyze-soil"
  to = "/.netlify/functions/analyze-soil"
  status = 200

[[redirects]]
<<<<<<< HEAD
  from = "/api/disease"
  to = "/.netlify/functions/disease-detection"
  status = 200

[[redirects]]
  from = "/api/market-insight"
  to = "/.netlify/functions/market-insight"
  status = 200

[[redirects]]
  from = "/api/weather"
  to = "/.netlify/functions/current-weather"
  status = 200
=======
  from = "/api/market-insight"
  to = "/.netlify/functions/market-insight"
  status = 200
>>>>>>> f88917de9e1179878ae13cf42269820599a2244a
