const KEY='smartCropFarmTwinV1';const $=id=>document.getElementById(id);const getFarm=()=>JSON.parse(localStorage.getItem(KEY)||'{}');
const scenario=$('scenario'), value=$('scenarioValue'), label=$('scenarioValueLabel'), cropWrap=$('cropSelectWrap');
scenario.addEventListener('change',()=>{const v=scenario.value;cropWrap.classList.toggle('hidden',v!=='crop');value.parentElement.classList.toggle('hidden',v==='crop');if(v==='rainfall'){label.firstChild.textContent='Rainfall change (%)';value.value=-20}else if(v==='temperature'){label.firstChild.textContent='Temperature change (°C)';value.value=3}else if(v==='water'){label.firstChild.textContent='Water availability change (%)';value.value=-30}else if(v==='soilph'){label.firstChild.textContent='pH change';value.value=-0.5}});
function riskScore(f){let s=0;let m=Number(f.moisture);if(m&&m<30)s+=2;else if(m&&m<45)s+=1;let t=Number(f.temperature);if(t>35)s+=2;else if(t>32)s+=1;let ph=Number(f.soilPH);if(ph&&(ph<5.5||ph>8))s+=2;return s}
function run(){const f=getFarm();const type=scenario.value;const v=Number(value.value)||0;const before=riskScore(f);let after=before,impact='Low change expected',action='Continue monitoring the field.';let current=f.currentCrop||'Current crop';let next=current;
if(type==='rainfall'){after+=v<=-30?2:v<0?1:0;impact=`Rainfall scenario: ${v}%`;action=v<0?'Monitor soil moisture and review irrigation timing.':'Review drainage and disease conditions if rainfall increases.'}
if(type==='temperature'){after+=v>=4?2:v>0?1:0;impact=`Temperature scenario: ${v} °C`;action=v>0?'Monitor heat stress, soil moisture and crop-stage sensitivity.':'Monitor cold-sensitive crop stages if temperature falls.'}
if(type==='water'){after+=v<=-40?2:v<0?1:0;impact=`Water availability scenario: ${v}%`;action=v<0?'Review irrigation priority and soil-moisture readings.':'Check whether excess water could create drainage or disease issues.'}
if(type==='crop'){next=$('altCrop').value;after=Math.max(0,before+(next.toLowerCase()==='rice'&&f.water==='Limited'?2:0));impact=`Crop scenario: ${current} → ${next}`;action='Compare local crop suitability, water needs, season and current market information before choosing.'}
if(type==='soilph'){after+=Math.abs(v)>=1?2:Math.abs(v)>=.5?1:0;impact=`Soil pH scenario: ${v>0?'+':''}${v}`;action='Re-test soil pH and use crop-specific nutrient guidance before changing inputs.'}
const level=n=>n>=4?'Higher':n>=2?'Moderate':'Lower';$('comparison').innerHTML=`<div class="compare-grid"><div class="compare-card"><h3>Current situation</h3><div class="metric"><span>Crop</span><b>${current}</b></div><div class="metric"><span>Risk signal</span><b>${level(before)}</b></div><div class="metric"><span>Farm data</span><b>Digital Twin</b></div></div><div class="compare-card"><h3>Scenario</h3><div class="metric"><span>Change</span><b>${impact}</b></div><div class="metric"><span>Risk signal</span><b>${level(after)}</b></div><div class="metric"><span>Crop</span><b>${next}</b></div></div><div class="compare-card"><h3>Suggested response</h3><div class="signal">${action}</div><div class="signal">Final decision stays with the farmer and should use local field observations.</div></div></div>`;}
$('simulate').addEventListener('click',run);run();
